# Generated by Django 4.1.7 on 2023-03-09 15:15

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Teachers',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('sub_expart', models.CharField(choices=[('BD', 'Big Data Engineer'), ('DA', 'Data Analyst'), ('DL', 'Deep Learning for NLP & Computer Vision With Python')], max_length=100)),
                ('email', models.EmailField(max_length=254)),
                ('profile_pic', models.ImageField(upload_to='teachersimg')),
                ('date_of_joinig', models.DateField(auto_now_add=True)),
            ],
        ),
    ]
