# Generated by Django 4.1.7 on 2023-03-16 16:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('index', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='AboutPage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200)),
                ('descriptions', models.TextField(max_length=300)),
                ('title_img', models.ImageField(upload_to='aboutimg')),
                ('testmonial_text', models.TextField(max_length=200)),
                ('testmonial_img', models.ImageField(upload_to='testmimg')),
            ],
        ),
    ]
